// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/ingest/v1/ingest.proto

package ingestv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestStatus int32

const (
	IngestStatus_INGEST_STATUS_UNSPECIFIED IngestStatus = 0
	IngestStatus_INGEST_STATUS_ACCEPTED    IngestStatus = 1
	IngestStatus_INGEST_STATUS_REJECTED    IngestStatus = 2
)

// Enum value maps for IngestStatus.
var (
	IngestStatus_name = map[int32]string{
		0: "INGEST_STATUS_UNSPECIFIED",
		1: "INGEST_STATUS_ACCEPTED",
		2: "INGEST_STATUS_REJECTED",
	}
	IngestStatus_value = map[string]int32{
		"INGEST_STATUS_UNSPECIFIED": 0,
		"INGEST_STATUS_ACCEPTED":    1,
		"INGEST_STATUS_REJECTED":    2,
	}
)

func (x IngestStatus) Enum() *IngestStatus {
	p := new(IngestStatus)
	*p = x
	return p
}

func (x IngestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IngestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ingest_v1_ingest_proto_enumTypes[0].Descriptor()
}

func (IngestStatus) Type() protoreflect.EnumType {
	return &file_proto_ingest_v1_ingest_proto_enumTypes[0]
}

func (x IngestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IngestStatus.Descriptor instead.
func (IngestStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_ingest_v1_ingest_proto_rawDescGZIP(), []int{0}
}

type Record struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*Record_Request
	//	*Record_Response
	Event         isRecord_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_proto_ingest_v1_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingest_v1_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_proto_ingest_v1_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetEvent() isRecord_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Record) GetRequest() *Request {
	if x != nil {
		if x, ok := x.Event.(*Record_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *Record) GetResponse() *Response {
	if x != nil {
		if x, ok := x.Event.(*Record_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isRecord_Event interface {
	isRecord_Event()
}

type Record_Request struct {
	Request *Request `protobuf:"bytes,1,opt,name=request,proto3,oneof"`
}

type Record_Response struct {
	Response *Response `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

func (*Record_Request) isRecord_Event() {}

func (*Record_Response) isRecord_Event() {}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_proto_ingest_v1_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingest_v1_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_proto_ingest_v1_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Metadata) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Metadata) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type HeaderValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderValues) Reset() {
	*x = HeaderValues{}
	mi := &file_proto_ingest_v1_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderValues) ProtoMessage() {}

func (x *HeaderValues) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingest_v1_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderValues.ProtoReflect.Descriptor instead.
func (*HeaderValues) Descriptor() ([]byte, []int) {
	return file_proto_ingest_v1_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *HeaderValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Method        string                   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]*HeaderValues `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	ContentLength int64                    `protobuf:"varint,5,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	Metadata      *Metadata                `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_ingest_v1_ingest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingest_v1_ingest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_ingest_v1_ingest_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Request) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Request) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Request) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

func (x *Request) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	StatusCode    int32                    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]*HeaderValues `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	ContentLength int64                    `protobuf:"varint,4,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	Metadata      *Metadata                `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_ingest_v1_ingest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingest_v1_ingest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_ingest_v1_ingest_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Response) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Response) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Response) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

func (x *Response) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type IngestAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Status        IngestStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=apiobserver.ingest.v1.IngestStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestAck) Reset() {
	*x = IngestAck{}
	mi := &file_proto_ingest_v1_ingest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestAck) ProtoMessage() {}

func (x *IngestAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingest_v1_ingest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestAck.ProtoReflect.Descriptor instead.
func (*IngestAck) Descriptor() ([]byte, []int) {
	return file_proto_ingest_v1_ingest_proto_rawDescGZIP(), []int{5}
}

func (x *IngestAck) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *IngestAck) GetStatus() IngestStatus {
	if x != nil {
		return x.Status
	}
	return IngestStatus_INGEST_STATUS_UNSPECIFIED
}

func (x *IngestAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IngestAck) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

var File_proto_ingest_v1_ingest_proto protoreflect.FileDescriptor

const file_proto_ingest_v1_ingest_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/ingest/v1/ingest.proto\x12\x15apiobserver.ingest.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x01\n" +
	"\x06Record\x12:\n" +
	"\arequest\x18\x01 \x01(\v2\x1e.apiobserver.ingest.v1.RequestH\x00R\arequest\x12=\n" +
	"\bresponse\x18\x02 \x01(\v2\x1f.apiobserver.ingest.v1.ResponseH\x00R\bresponseB\a\n" +
	"\x05event\"{\n" +
	"\bMetadata\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"&\n" +
	"\fHeaderValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xd3\x02\n" +
	"\aRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12E\n" +
	"\aheaders\x18\x03 \x03(\v2+.apiobserver.ingest.v1.Request.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12%\n" +
	"\x0econtent_length\x18\x05 \x01(\x03R\rcontentLength\x12;\n" +
	"\bmetadata\x18\x06 \x01(\v2\x1f.apiobserver.ingest.v1.MetadataR\bmetadata\x1a_\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.apiobserver.ingest.v1.HeaderValuesR\x05value:\x028\x01\"\xcc\x02\n" +
	"\bResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12F\n" +
	"\aheaders\x18\x02 \x03(\v2,.apiobserver.ingest.v1.Response.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12%\n" +
	"\x0econtent_length\x18\x04 \x01(\x03R\rcontentLength\x12;\n" +
	"\bmetadata\x18\x05 \x01(\v2\x1f.apiobserver.ingest.v1.MetadataR\bmetadata\x1a_\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.apiobserver.ingest.v1.HeaderValuesR\x05value:\x028\x01\"\x9d\x01\n" +
	"\tIngestAck\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12;\n" +
	"\x06status\x18\x02 \x01(\x0e2#.apiobserver.ingest.v1.IngestStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable*e\n" +
	"\fIngestStatus\x12\x1d\n" +
	"\x19INGEST_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16INGEST_STATUS_ACCEPTED\x10\x01\x12\x1a\n" +
	"\x16INGEST_STATUS_REJECTED\x10\x022^\n" +
	"\rIngestService\x12M\n" +
	"\x06Ingest\x12\x1d.apiobserver.ingest.v1.Record\x1a .apiobserver.ingest.v1.IngestAck(\x010\x01B'Z%api-observer/proto/ingest/v1;ingestv1b\x06proto3"

var (
	file_proto_ingest_v1_ingest_proto_rawDescOnce sync.Once
	file_proto_ingest_v1_ingest_proto_rawDescData []byte
)

func file_proto_ingest_v1_ingest_proto_rawDescGZIP() []byte {
	file_proto_ingest_v1_ingest_proto_rawDescOnce.Do(func() {
		file_proto_ingest_v1_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ingest_v1_ingest_proto_rawDesc), len(file_proto_ingest_v1_ingest_proto_rawDesc)))
	})
	return file_proto_ingest_v1_ingest_proto_rawDescData
}

var file_proto_ingest_v1_ingest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_ingest_v1_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_ingest_v1_ingest_proto_goTypes = []any{
	(IngestStatus)(0),             // 0: apiobserver.ingest.v1.IngestStatus
	(*Record)(nil),                // 1: apiobserver.ingest.v1.Record
	(*Metadata)(nil),              // 2: apiobserver.ingest.v1.Metadata
	(*HeaderValues)(nil),          // 3: apiobserver.ingest.v1.HeaderValues
	(*Request)(nil),               // 4: apiobserver.ingest.v1.Request
	(*Response)(nil),              // 5: apiobserver.ingest.v1.Response
	(*IngestAck)(nil),             // 6: apiobserver.ingest.v1.IngestAck
	nil,                           // 7: apiobserver.ingest.v1.Request.HeadersEntry
	nil,                           // 8: apiobserver.ingest.v1.Response.HeadersEntry
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_proto_ingest_v1_ingest_proto_depIdxs = []int32{
	4,  // 0: apiobserver.ingest.v1.Record.request:type_name -> apiobserver.ingest.v1.Request
	5,  // 1: apiobserver.ingest.v1.Record.response:type_name -> apiobserver.ingest.v1.Response
	9,  // 2: apiobserver.ingest.v1.Metadata.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 3: apiobserver.ingest.v1.Request.headers:type_name -> apiobserver.ingest.v1.Request.HeadersEntry
	2,  // 4: apiobserver.ingest.v1.Request.metadata:type_name -> apiobserver.ingest.v1.Metadata
	8,  // 5: apiobserver.ingest.v1.Response.headers:type_name -> apiobserver.ingest.v1.Response.HeadersEntry
	2,  // 6: apiobserver.ingest.v1.Response.metadata:type_name -> apiobserver.ingest.v1.Metadata
	0,  // 7: apiobserver.ingest.v1.IngestAck.status:type_name -> apiobserver.ingest.v1.IngestStatus
	3,  // 8: apiobserver.ingest.v1.Request.HeadersEntry.value:type_name -> apiobserver.ingest.v1.HeaderValues
	3,  // 9: apiobserver.ingest.v1.Response.HeadersEntry.value:type_name -> apiobserver.ingest.v1.HeaderValues
	1,  // 10: apiobserver.ingest.v1.IngestService.Ingest:input_type -> apiobserver.ingest.v1.Record
	6,  // 11: apiobserver.ingest.v1.IngestService.Ingest:output_type -> apiobserver.ingest.v1.IngestAck
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_ingest_v1_ingest_proto_init() }
func file_proto_ingest_v1_ingest_proto_init() {
	if File_proto_ingest_v1_ingest_proto != nil {
		return
	}
	file_proto_ingest_v1_ingest_proto_msgTypes[0].OneofWrappers = []any{
		(*Record_Request)(nil),
		(*Record_Response)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ingest_v1_ingest_proto_rawDesc), len(file_proto_ingest_v1_ingest_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ingest_v1_ingest_proto_goTypes,
		DependencyIndexes: file_proto_ingest_v1_ingest_proto_depIdxs,
		EnumInfos:         file_proto_ingest_v1_ingest_proto_enumTypes,
		MessageInfos:      file_proto_ingest_v1_ingest_proto_msgTypes,
	}.Build()
	File_proto_ingest_v1_ingest_proto = out.File
	file_proto_ingest_v1_ingest_proto_goTypes = nil
	file_proto_ingest_v1_ingest_proto_depIdxs = nil
}
