// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/query/v1/query.proto

package queryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectorId   string                 `protobuf:"bytes,1,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoReply) Reset() {
	*x = InfoReply{}
	mi := &file_proto_query_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoReply) ProtoMessage() {}

func (x *InfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoReply.ProtoReflect.Descriptor instead.
func (*InfoReply) Descriptor() ([]byte, []int) {
	return file_proto_query_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *InfoReply) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

type LogParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Cursor        int64                  `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogParams) Reset() {
	*x = LogParams{}
	mi := &file_proto_query_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogParams) ProtoMessage() {}

func (x *LogParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogParams.ProtoReflect.Descriptor instead.
func (*LogParams) Descriptor() ([]byte, []int) {
	return file_proto_query_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *LogParams) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *LogParams) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *LogParams) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

type Log struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Cursor int64                  `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*Log_Request
	//	*Log_Response
	Event         isLog_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_proto_query_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_proto_query_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *Log) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *Log) GetEvent() isLog_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Log) GetRequest() *Request {
	if x != nil {
		if x, ok := x.Event.(*Log_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *Log) GetResponse() *Response {
	if x != nil {
		if x, ok := x.Event.(*Log_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isLog_Event interface {
	isLog_Event()
}

type Log_Request struct {
	Request *Request `protobuf:"bytes,2,opt,name=request,proto3,oneof"`
}

type Log_Response struct {
	Response *Response `protobuf:"bytes,3,opt,name=response,proto3,oneof"`
}

func (*Log_Request) isLog_Event() {}

func (*Log_Response) isLog_Event() {}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_proto_query_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_proto_query_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *Metadata) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Metadata) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Metadata) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type HeaderValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderValues) Reset() {
	*x = HeaderValues{}
	mi := &file_proto_query_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderValues) ProtoMessage() {}

func (x *HeaderValues) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderValues.ProtoReflect.Descriptor instead.
func (*HeaderValues) Descriptor() ([]byte, []int) {
	return file_proto_query_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *HeaderValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Method        string                   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]*HeaderValues `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	ContentLength int64                    `protobuf:"varint,5,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	Metadata      *Metadata                `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_query_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_query_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Request) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Request) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Request) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

func (x *Request) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	StatusCode    int32                    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]*HeaderValues `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	ContentLength int64                    `protobuf:"varint,4,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	Metadata      *Metadata                `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_query_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_query_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *Response) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Response) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Response) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Response) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

func (x *Response) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_query_v1_query_proto protoreflect.FileDescriptor

const file_proto_query_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/query/v1/query.proto\x12\x14apiobserver.query.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\".\n" +
	"\tInfoReply\x12!\n" +
	"\fcollector_id\x18\x01 \x01(\tR\vcollectorId\"\x95\x01\n" +
	"\tLogParams\x129\n" +
	"\n" +
	"start_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\x03R\x06cursor\"\x9f\x01\n" +
	"\x03Log\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\x03R\x06cursor\x129\n" +
	"\arequest\x18\x02 \x01(\v2\x1d.apiobserver.query.v1.RequestH\x00R\arequest\x12<\n" +
	"\bresponse\x18\x03 \x01(\v2\x1e.apiobserver.query.v1.ResponseH\x00R\bresponseB\a\n" +
	"\x05event\"{\n" +
	"\bMetadata\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"&\n" +
	"\fHeaderValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xd0\x02\n" +
	"\aRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12D\n" +
	"\aheaders\x18\x03 \x03(\v2*.apiobserver.query.v1.Request.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12%\n" +
	"\x0econtent_length\x18\x05 \x01(\x03R\rcontentLength\x12:\n" +
	"\bmetadata\x18\x06 \x01(\v2\x1e.apiobserver.query.v1.MetadataR\bmetadata\x1a^\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".apiobserver.query.v1.HeaderValuesR\x05value:\x028\x01\"\xc9\x02\n" +
	"\bResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12E\n" +
	"\aheaders\x18\x02 \x03(\v2+.apiobserver.query.v1.Response.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12%\n" +
	"\x0econtent_length\x18\x04 \x01(\x03R\rcontentLength\x12:\n" +
	"\bmetadata\x18\x05 \x01(\v2\x1e.apiobserver.query.v1.MetadataR\bmetadata\x1a^\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".apiobserver.query.v1.HeaderValuesR\x05value:\x028\x012\x94\x01\n" +
	"\n" +
	"LogService\x12?\n" +
	"\x04Info\x12\x16.google.protobuf.Empty\x1a\x1f.apiobserver.query.v1.InfoReply\x12E\n" +
	"\x05Query\x12\x1f.apiobserver.query.v1.LogParams\x1a\x19.apiobserver.query.v1.Log0\x01B%Z#api-observer/proto/query/v1;queryv1b\x06proto3"

var (
	file_proto_query_v1_query_proto_rawDescOnce sync.Once
	file_proto_query_v1_query_proto_rawDescData []byte
)

func file_proto_query_v1_query_proto_rawDescGZIP() []byte {
	file_proto_query_v1_query_proto_rawDescOnce.Do(func() {
		file_proto_query_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_query_v1_query_proto_rawDesc), len(file_proto_query_v1_query_proto_rawDesc)))
	})
	return file_proto_query_v1_query_proto_rawDescData
}

var file_proto_query_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_query_v1_query_proto_goTypes = []any{
	(*InfoReply)(nil),             // 0: apiobserver.query.v1.InfoReply
	(*LogParams)(nil),             // 1: apiobserver.query.v1.LogParams
	(*Log)(nil),                   // 2: apiobserver.query.v1.Log
	(*Metadata)(nil),              // 3: apiobserver.query.v1.Metadata
	(*HeaderValues)(nil),          // 4: apiobserver.query.v1.HeaderValues
	(*Request)(nil),               // 5: apiobserver.query.v1.Request
	(*Response)(nil),              // 6: apiobserver.query.v1.Response
	nil,                           // 7: apiobserver.query.v1.Request.HeadersEntry
	nil,                           // 8: apiobserver.query.v1.Response.HeadersEntry
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 10: google.protobuf.Empty
}
var file_proto_query_v1_query_proto_depIdxs = []int32{
	9,  // 0: apiobserver.query.v1.LogParams.start_date:type_name -> google.protobuf.Timestamp
	9,  // 1: apiobserver.query.v1.LogParams.end_date:type_name -> google.protobuf.Timestamp
	5,  // 2: apiobserver.query.v1.Log.request:type_name -> apiobserver.query.v1.Request
	6,  // 3: apiobserver.query.v1.Log.response:type_name -> apiobserver.query.v1.Response
	9,  // 4: apiobserver.query.v1.Metadata.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 5: apiobserver.query.v1.Request.headers:type_name -> apiobserver.query.v1.Request.HeadersEntry
	3,  // 6: apiobserver.query.v1.Request.metadata:type_name -> apiobserver.query.v1.Metadata
	8,  // 7: apiobserver.query.v1.Response.headers:type_name -> apiobserver.query.v1.Response.HeadersEntry
	3,  // 8: apiobserver.query.v1.Response.metadata:type_name -> apiobserver.query.v1.Metadata
	4,  // 9: apiobserver.query.v1.Request.HeadersEntry.value:type_name -> apiobserver.query.v1.HeaderValues
	4,  // 10: apiobserver.query.v1.Response.HeadersEntry.value:type_name -> apiobserver.query.v1.HeaderValues
	10, // 11: apiobserver.query.v1.LogService.Info:input_type -> google.protobuf.Empty
	1,  // 12: apiobserver.query.v1.LogService.Query:input_type -> apiobserver.query.v1.LogParams
	0,  // 13: apiobserver.query.v1.LogService.Info:output_type -> apiobserver.query.v1.InfoReply
	2,  // 14: apiobserver.query.v1.LogService.Query:output_type -> apiobserver.query.v1.Log
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_query_v1_query_proto_init() }
func file_proto_query_v1_query_proto_init() {
	if File_proto_query_v1_query_proto != nil {
		return
	}
	file_proto_query_v1_query_proto_msgTypes[2].OneofWrappers = []any{
		(*Log_Request)(nil),
		(*Log_Response)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_query_v1_query_proto_rawDesc), len(file_proto_query_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_query_v1_query_proto_goTypes,
		DependencyIndexes: file_proto_query_v1_query_proto_depIdxs,
		MessageInfos:      file_proto_query_v1_query_proto_msgTypes,
	}.Build()
	File_proto_query_v1_query_proto = out.File
	file_proto_query_v1_query_proto_goTypes = nil
	file_proto_query_v1_query_proto_depIdxs = nil
}
